# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62b8307f02124a64348baf18f1c46bd8d877d3a636c66cd4cfb4051972fbb1895641e842fb5192f1eeb35d3fd2e7db3647a60bc782e287ab3ffc764ea7bc424a

test:
  secret_key_base: 72fc7ecae5886fc633d8b5108d70de493de67b63fb26ca2bc54dec88d289249245240950a3f2808c49280180cd83185b6491de6e80602cb741d306db094123d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
